name: Month End Transaction Entry

on:
  #push: # For testing
  schedule:
    # Second day of the Month
    - cron: 0 0 2 * *

jobs:
  data-entry:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Set up Chrome and ChromeDriver
      run: |
       chmod +x ./scripts/setup.sh
        ./scripts/setup.sh

    - name: Compile with Maven
      run: mvn compile 

    - name: Run Program  
      run: mvn exec:java -Dexec.mainClass=automate.Automation -Dexec.cleanupDaemonThreads=false -Dexec.args="January 2022 January 2022" -e
      env:
        SHARESIES_USERNAME: ${{ secrets.SHARESIES_USERNAME }}
        SHARESIES_PASSWORD: ${{ secrets.SHARESIES_PASSWORD }}
        YAHOO_USERNAME: ${{ secrets.YAHOO_USERNAME }}
        YAHOO_PASSWORD: ${{ secrets.YAHOO_PASSWORD }}
    
    - name: Send Screenshot through mail
      if: ${{ failure() && steps.mainProgram.conclusion == 'failure' }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions - Main Program failed
        to: pravinmanoj44@gmail.com
        from: Pravin Modotholi 
        secure: true
        attachments: ./screenshots/*.png